import unittest

from scripts.validate_handoff import validate


VALID_REVIEW = """# Agent Relay Review

## Mission
Review the implementation.

## Reviewer profile
- Role: Reviewer
- Review lenses: design

## Reviewed state
- Immutable snapshot: abc123

## Mutation boundaries
- Strictly read-only / forbidden: repository writes

## Evidence baseline
- source inspection

## Findings summary
- Open: 0

## Structured findings
None.

## Executed or inspectable evidence
- source inspection at abc123

## Unverified surfaces
- runtime behavior

## Recommended next role/pass
- Verifier: reproduce runtime behavior

## Readiness/sign-off status
Not assessed.

## Provenance
Generated by: test agent
Agent Relay role: Reviewer
Source snapshot: abc123
"""


class RecordValidatorTests(unittest.TestCase):
    def test_review_record_is_auto_detected(self):
        self.assertEqual(validate(VALID_REVIEW), [])

    def test_review_requires_provenance(self):
        text = VALID_REVIEW.replace("## Provenance\n", "## Attribution\n")
        self.assertIn("missing heading: Provenance", validate(text))

    def test_review_requires_explicit_mutation_boundary(self):
        text = VALID_REVIEW.replace(
            "- Strictly read-only / forbidden: repository writes",
            "- No repository constraints recorded",
        )
        self.assertIn(
            "mutation boundary is not explicit (no read-only/forbidden statement)",
            validate(text),
        )

    def test_review_template_placeholders_fail(self):
        text = VALID_REVIEW.replace("test agent", "<agent/client>")
        self.assertIn("template placeholders appear to remain unfilled", validate(text))


if __name__ == "__main__":
    unittest.main()
