import unittest

from scripts.validate_handoff import validate


VALID_REVIEW = """# Agent Relay Review

## Mission
Review the implementation.

## Reviewer profile
- Role: Reviewer
- Review lenses: design
- Role/lens source: inferred

## Reviewed state
- Immutable snapshot: abc123

## Mutation boundaries
- Strictly read-only / forbidden: repository writes

## Evidence baseline
- source inspection

## Findings summary
- Open: 0

## Structured findings
None.

## Executed or inspectable evidence
- source inspection at abc123

## Unverified surfaces
- runtime behavior

## Recommended next role/pass
- Verifier: reproduce runtime behavior

## Readiness/sign-off status
Not assessed.

## Provenance
Generated by: test agent
Agent Relay role: Reviewer
Source snapshot: abc123
"""

LEGACY_HANDOFF = """# Agent Relay Handoff

## Mission
Continue the work.

## Current role
Reviewer

## Role source
Inferred from workflow state

## Recommended role sequence
Reviewer -> Verifier

## Authoritative substrate
Repository

## Current immutable snapshot
- Primary state: abc123

## Mutation permissions
### Allowed
- none
### Strictly read-only / forbidden
- repository writes

## Completed work
- review completed

## Verified evidence
- source inspection at abc123

## Open findings
- none

## Ordered next actions
1. verify

## Verification checkpoint
Verify the reviewed claim.

## Completion criteria
- verification complete
"""

VALID_PASS = """# Agent Pass Record

Agent pass: review-pass
Role: reviewer
Role source: inferred
Role sequence: reviewer -> verifier
Reviewed/modified snapshot: abc123
Environment: source inspection only

Findings: 0
Fixed: 0
Disproved: 0
Deferred: 0
Blocked: 0

Executable/inspectable evidence:
- source inspection at abc123

Verification checkpoint:
- runtime reproduction

Unverified:
- runtime

Next recommended role/pass:
- verifier: reproduce runtime

Provenance:
- Generated by: test agent
- Source snapshot: abc123
"""


class RecordValidatorTests(unittest.TestCase):
    def test_review_record_is_auto_detected(self):
        self.assertEqual(validate(VALID_REVIEW), [])

    def test_retitled_review_is_detected_by_structure(self):
        text = VALID_REVIEW.replace("# Agent Relay Review", "# Review pass for PR 2")
        self.assertEqual(validate(text), [])

    def test_handoff_mentioning_review_title_is_not_misclassified(self):
        text = LEGACY_HANDOFF.replace(
            "- review completed",
            "- discussed `# Agent Relay Review` in completed-work prose",
        )
        self.assertEqual(validate(text), [])

    def test_review_requires_provenance(self):
        text = VALID_REVIEW.replace("## Provenance\n", "## Attribution\n")
        self.assertIn("missing heading: Provenance", validate(text))

    def test_review_requires_explicit_mutation_boundary(self):
        text = VALID_REVIEW.replace(
            "- Strictly read-only / forbidden: repository writes",
            "- No repository constraints recorded",
        )
        self.assertIn(
            "mutation boundary is not explicit (no read-only/forbidden statement)",
            validate(text),
        )

    def test_any_angle_bracket_placeholder_fails(self):
        for placeholder in (
            "<explicit | inferred>",
            "<count>",
            "<expected>",
            "<observed>",
            "<resources and exact prohibition>",
            "<agent/client>",
        ):
            with self.subTest(placeholder=placeholder):
                text = VALID_REVIEW.replace("test agent", placeholder)
                self.assertIn(
                    "template placeholders appear to remain unfilled",
                    validate(text),
                )

    def test_v02_handoff_without_new_optional_headings_remains_valid(self):
        self.assertEqual(validate(LEGACY_HANDOFF), [])

    def test_agent_pass_record_is_supported(self):
        self.assertEqual(validate(VALID_PASS), [])

    def test_agent_pass_placeholders_fail(self):
        text = VALID_PASS.replace("abc123", "<immutable-id>")
        self.assertIn("template placeholders appear to remain unfilled", validate(text))

    def test_unknown_record_kind_fails_closed(self):
        self.assertEqual(
            validate("# Miscellaneous note\n\nNothing structured here."),
            ["could not determine record kind; pass --kind"],
        )


if __name__ == "__main__":
    unittest.main()
