"""v0.5 structural tests: delegation briefs and authority provenance.

The v0.5 addition is orchestrated delegation, where authority reaches a
subordinate pass through an intermediary. A relayed statement about authority
is not authority, so the brief record fails closed: an asserted grant must cite
its grantor, its verbatim scope, and when it was granted, or the dispatching
agent must record the scope as its own judgment instead.
"""

import pathlib
import unittest

from scripts.validate_handoff import _detect_kind, validate


VALID_BRIEF = """# Agent Relay Delegation Brief

## Mission
Repair the state-write symlink window.

## Mission mode
fix

## Lane
The state-write path only. The CLI construction path belongs to another lane.

## Authority provenance
- Source: owner-grant
- Grantor: mission owner
- Granted scope (verbatim): "fix the state-write symlink window"
- Granted at: 2026-09-05, against snapshot e6c6874

## Assurance profile
consequential

## Authoritative substrate
Repository under review.

## Current immutable snapshot
- Primary state: e6c6874
- Related states: none

## Mutation boundaries
### Allowed
- the state-write module and its regression module, in a private working copy

### Strictly read-only / forbidden
- durable records, review threads, and PR state are forbidden to this pass

## Centrally owned derived claims
- test counts are owned by the dispatching agent; report the inputs instead

## Required deliverables
- a patch file carrying the fix and its regression

## Return contract
- Declared deviations: required, or `none`
- Claim maturity ceiling: EXECUTED

## Completion criteria
- the regression fails at the pre-fix state and passes with the fix

## Provenance
Generated by: test agent
Agent Relay role: Integrator
Source snapshot: e6c6874
"""


def _without_section(text: str, heading: str) -> str:
    """Drop one `##` section, keeping the rest of the record intact."""

    lines = text.splitlines()
    start = next(
        index for index, line in enumerate(lines) if line.strip() == f"## {heading}"
    )
    end = next(
        (
            index
            for index in range(start + 1, len(lines))
            if lines[index].startswith("## ")
        ),
        len(lines),
    )
    return "\n".join(lines[:start] + lines[end:])


class DelegationBriefValidatorTests(unittest.TestCase):
    """A brief is a distinct record kind with its own minimum."""

    def test_filled_brief_passes(self):
        self.assertEqual(validate(VALID_BRIEF), [])

    def test_brief_is_detected_from_its_title(self):
        self.assertEqual(_detect_kind(VALID_BRIEF), "brief")

    def test_missing_required_heading_is_reported(self):
        text = _without_section(VALID_BRIEF, "Required deliverables")
        self.assertIn("missing heading: Required deliverables", validate(text))

    def test_brief_mutation_boundary_must_be_explicit(self):
        text = VALID_BRIEF.replace(
            "### Strictly read-only / forbidden\n"
            "- durable records, review threads, and PR state are forbidden to this pass",
            "### Notes\n- work carefully",
        )
        self.assertIn(
            "mutation boundary is not explicit (no read-only/forbidden statement)",
            validate(text),
        )

    def test_brief_shares_the_mission_mode_vocabulary(self):
        text = VALID_BRIEF.replace("## Mission mode\nfix", "## Mission mode\nrepair")
        self.assertIn("invalid mission mode: repair", validate(text))

    def test_adding_the_brief_kind_did_not_break_handoff_detection(self):
        handoff = (pathlib.Path(__file__).resolve().parent.parent / "assets" / "HANDOFF.md").read_text(
            encoding="utf-8"
        )
        self.assertEqual(_detect_kind(handoff), "handoff")


class AuthorityProvenanceTests(unittest.TestCase):
    """An asserted grant must be citable, or recorded as judgment."""

    def _errors(self, text):
        return [error for error in validate(text) if "authority provenance" in error]

    def test_owner_grant_without_a_grantor_is_refused(self):
        text = VALID_BRIEF.replace("- Grantor: mission owner", "- Grantor: N/A")
        self.assertTrue(
            any("Grantor" in error for error in self._errors(text)), self._errors(text)
        )

    def test_owner_grant_without_a_verbatim_scope_is_refused(self):
        text = VALID_BRIEF.replace(
            '- Granted scope (verbatim): "fix the state-write symlink window"',
            "- Granted scope (verbatim): none",
        )
        self.assertTrue(
            any("verbatim" in error for error in self._errors(text)), self._errors(text)
        )

    def test_owner_grant_without_a_grant_time_is_refused(self):
        text = VALID_BRIEF.replace(
            "- Granted at: 2026-09-05, against snapshot e6c6874",
            "- Granted at: unknown",
        )
        self.assertTrue(
            any("Granted at" in error for error in self._errors(text)),
            self._errors(text),
        )

    def test_a_dropped_grant_field_is_refused_like_an_empty_one(self):
        text = VALID_BRIEF.replace("- Grantor: mission owner\n", "")
        self.assertTrue(
            any("Grantor" in error for error in self._errors(text)), self._errors(text)
        )

    def test_delegated_grant_must_also_cite_its_grant(self):
        text = VALID_BRIEF.replace(
            "- Source: owner-grant", "- Source: delegated-grant"
        ).replace("- Grantor: mission owner", "- Grantor: N/A")
        self.assertTrue(
            any("delegated-grant" in error for error in self._errors(text)),
            self._errors(text),
        )

    def test_orchestrator_judgment_needs_no_grantor(self):
        text = (
            VALID_BRIEF.replace("- Source: owner-grant", "- Source: orchestrator-judgment")
            .replace("- Grantor: mission owner", "- Grantor: N/A")
            .replace(
                '- Granted scope (verbatim): "fix the state-write symlink window"',
                "- Granted scope (verbatim): N/A",
            )
            .replace(
                "- Granted at: 2026-09-05, against snapshot e6c6874",
                "- Granted at: N/A",
            )
        )
        self.assertEqual(validate(text), [])

    def test_no_conveyed_authority_needs_no_grantor(self):
        text = (
            VALID_BRIEF.replace("- Source: owner-grant", "- Source: none")
            .replace("- Grantor: mission owner", "- Grantor: N/A")
            .replace(
                '- Granted scope (verbatim): "fix the state-write symlink window"',
                "- Granted scope (verbatim): N/A",
            )
            .replace(
                "- Granted at: 2026-09-05, against snapshot e6c6874",
                "- Granted at: N/A",
            )
        )
        self.assertEqual(validate(text), [])

    def test_unrecognized_authority_source_is_refused(self):
        text = VALID_BRIEF.replace("- Source: owner-grant", "- Source: implied")
        self.assertIn("invalid authority provenance source: implied", validate(text))

    def test_absent_authority_source_is_refused(self):
        text = VALID_BRIEF.replace("- Source: owner-grant", "- Source: N/A")
        self.assertTrue(
            any("must declare an authority provenance source" in error for error in validate(text))
        )

    def test_a_fenced_example_cannot_supply_the_authority_source(self):
        text = VALID_BRIEF.replace(
            "- Source: owner-grant",
            "```\n- Source: owner-grant\n```",
        )
        self.assertTrue(
            any("must declare an authority provenance source" in error for error in validate(text))
        )


class DelegationBriefTemplateTests(unittest.TestCase):
    """The shipped template must satisfy the minimum it teaches."""

    ROOT = pathlib.Path(__file__).resolve().parent.parent

    def setUp(self):
        self.text = (self.ROOT / "assets" / "DELEGATION-BRIEF.md").read_text(
            encoding="utf-8"
        )

    def test_template_is_titled_as_a_brief(self):
        self.assertTrue(self.text.startswith("# Agent Relay Delegation Brief"))

    def test_template_carries_every_required_heading(self):
        from scripts.validate_handoff import BRIEF_REQUIRED_HEADINGS

        for heading in BRIEF_REQUIRED_HEADINGS:
            with self.subTest(heading=heading):
                self.assertIn(f"## {heading}", self.text)

    def test_template_carries_every_authority_provenance_field(self):
        for field in (
            "- Source:",
            "- Grantor:",
            "- Granted scope (verbatim):",
            "- Granted at:",
        ):
            with self.subTest(field=field):
                self.assertIn(field, self.text)

    def test_template_offers_the_whole_authority_vocabulary(self):
        for source in (
            "owner-grant",
            "delegated-grant",
            "orchestrator-judgment",
            "none",
        ):
            with self.subTest(source=source):
                self.assertIn(source, self.text)

    def test_template_requires_declared_deviations(self):
        self.assertIn("Declared deviations:", self.text)


class ProtocolV05DocumentationTests(unittest.TestCase):
    """Version and ownership invariants for the v0.5 additions."""

    ROOT = pathlib.Path(__file__).resolve().parent.parent

    def test_skill_and_readme_declare_the_same_version(self):
        skill = (self.ROOT / "SKILL.md").read_text(encoding="utf-8")
        readme = (self.ROOT / "README.md").read_text(encoding="utf-8")
        declared = next(
            line.split(":", 1)[1].strip().strip('"')
            for line in skill.splitlines()
            if line.strip().startswith("version:")
        )
        self.assertIn(f"**{declared}**", readme)

    def test_provenance_records_the_declared_version(self):
        skill = (self.ROOT / "SKILL.md").read_text(encoding="utf-8")
        declared = next(
            line.split(":", 1)[1].strip().strip('"')
            for line in skill.splitlines()
            if line.strip().startswith("version:")
        )
        provenance = (self.ROOT / "PROVENANCE.md").read_text(encoding="utf-8")
        self.assertIn(declared, provenance)

    def test_orchestrated_delegation_is_linked_from_the_skill(self):
        skill = (self.ROOT / "SKILL.md").read_text(encoding="utf-8")
        self.assertIn("references/orchestrated-delegation.md", skill)

    def test_delegation_brief_asset_is_linked_from_the_skill(self):
        skill = (self.ROOT / "SKILL.md").read_text(encoding="utf-8")
        self.assertIn("assets/DELEGATION-BRIEF.md", skill)

    def test_authority_vocabulary_has_exactly_one_owning_document(self):
        docs = list(self.ROOT.glob("*.md")) + list(self.ROOT.glob("*/*.md"))
        owners = [
            doc
            for doc in docs
            if "| `owner-grant` |" in doc.read_text(encoding="utf-8")
        ]
        self.assertEqual(
            [doc.name for doc in owners], ["orchestrated-delegation.md"]
        )

    def test_relayed_authority_rule_is_stated_in_the_rule_list(self):
        skill = (self.ROOT / "SKILL.md").read_text(encoding="utf-8")
        rules = skill.split("## Non-negotiable rules", 1)[1].split("\n## ", 1)[0]
        self.assertIn("Relayed authority is not authority", rules)


# The main guard stays below every v0.5 test class so direct module execution
# cannot silently skip later classes (regression for upstream PR #12).
if __name__ == "__main__":
    unittest.main()
