import unittest

from scripts.validate_handoff import validate


BASE_PASS = """# Agent Pass Record

Agent pass: v04-test
Role: builder
Review lenses: N/A
Role source: explicit
Role sequence: builder -> verifier
Reviewed/modified snapshot: abc123

Findings: 0
Fixed: 0
Disproved: 0
Deferred: 0
Blocked: 0

Executable/inspectable evidence:
- source inspection at abc123

Verification checkpoint:
- verify the claim

Unverified:
- runtime

Next recommended role/pass:
- verifier: verify

Provenance:
- Generated by: test agent
- Source snapshot: abc123
"""


class V04PassMetadataTests(unittest.TestCase):
    def test_optional_v04_fields_validate_when_explicit(self):
        text = BASE_PASS.replace(
            "Reviewed/modified snapshot: abc123",
            """Mission mode: build
Mission anchor: sha256:abc
Decision authority: implementation=builder; readiness=integrator
Assurance profile: standard
Mutation boundary: allowed src/**; read-only specs/**
Reviewed/modified snapshot: abc123
Execution status: EXECUTED
Termination reason: N/A""",
        )
        self.assertEqual(validate(text, kind="pass"), [])

    def test_pass_boundary_fails_when_vague(self):
        text = BASE_PASS.replace(
            "Reviewed/modified snapshot: abc123",
            "Mutation boundary: constraints recorded elsewhere\nReviewed/modified snapshot: abc123",
        )
        self.assertIn(
            "pass mutation boundary is not explicit (no allowed/read-only/forbidden statement)",
            validate(text, kind="pass"),
        )

    def test_optional_vocabularies_fail_closed(self):
        cases = {
            "Mission mode: invent": "invalid mission mode: invent",
            "Assurance profile: maximum": "invalid assurance profile: maximum",
            "Execution status: SUCCESS": "invalid execution status: SUCCESS",
            "Termination reason: LGTM": "invalid termination reason: LGTM",
        }
        for field, expected in cases.items():
            with self.subTest(field=field):
                text = BASE_PASS.replace(
                    "Reviewed/modified snapshot: abc123",
                    field + "\nReviewed/modified snapshot: abc123",
                )
                self.assertIn(expected, validate(text, kind="pass"))


class ColdStartStructureTests(unittest.TestCase):
    def test_empty_open_findings_section_is_not_cold_start_ready(self):
        handoff = """# Agent Relay Handoff

## Mission
Continue.
## Current role
Builder
## Role source
Explicit
## Recommended role sequence
Builder -> Verifier
## Authoritative substrate
Repository
## Current immutable snapshot
abc123
## Mutation permissions
Strictly read-only / forbidden: specs
## Completed work
Done.
## Verified evidence
None.
## Open findings

## Ordered next actions
1. Verify.
## Verification checkpoint
Verify.
## Completion criteria
Done.
"""
        self.assertIn(
            "open findings section must say `None.` or carry findings",
            validate(handoff, kind="handoff"),
        )

    def test_finding_table_must_preserve_snapshot_column(self):
        handoff = """# Agent Relay Handoff

## Mission
Continue.
## Current role
Builder
## Role source
Explicit
## Recommended role sequence
Builder -> Verifier
## Authoritative substrate
Repository
## Current immutable snapshot
abc123
## Mutation permissions
Strictly read-only / forbidden: specs
## Completed work
Done.
## Verified evidence
None.
## Open findings
| Finding | State |
|---|---|
| F1 | OPEN |
## Ordered next actions
1. Verify.
## Verification checkpoint
Verify.
## Completion criteria
Done.
"""
        self.assertIn(
            "open finding table must preserve an observation/reviewed snapshot",
            validate(handoff, kind="handoff"),
        )


if __name__ == "__main__":
    unittest.main()
