import pathlib
import re
import unittest

from scripts.validate_handoff import validate


VALID_REVIEW = """# Agent Relay Review

## Mission
Review the implementation.

## Reviewer profile
- Role: Reviewer
- Review lenses: design
- Role/lens source: inferred

## Reviewed state
- Immutable snapshot: abc123

## Mutation boundaries
- Strictly read-only / forbidden: repository writes

## Evidence baseline
- source inspection

## Findings summary
- Open: 0

## Structured findings
None.

## Executed or inspectable evidence
- source inspection at abc123

## Unverified surfaces
- runtime behavior

## Recommended next role/pass
- Verifier: reproduce runtime behavior

## Readiness/sign-off status
Not assessed.

## Provenance
Generated by: test agent
Agent Relay role: Reviewer
Source snapshot: abc123
"""

LEGACY_HANDOFF = """# Agent Relay Handoff

## Mission
Continue the work.

## Current role
Reviewer

## Role source
Inferred from workflow state

## Recommended role sequence
Reviewer -> Verifier

## Authoritative substrate
Repository

## Current immutable snapshot
- Primary state: abc123

## Mutation permissions
### Allowed
- none
### Strictly read-only / forbidden
- repository writes

## Completed work
- review completed

## Verified evidence
- source inspection at abc123

## Open findings
- none

## Ordered next actions
1. verify

## Verification checkpoint
Verify the reviewed claim.

## Completion criteria
- verification complete
"""

VALID_PASS = """# Agent Pass Record

Agent pass: review-pass
Role: reviewer
Review lenses: design
Role source: inferred
Role sequence: reviewer -> verifier
Reviewed/modified snapshot: abc123
Environment: source inspection only

Findings: 0
Fixed: 0
Disproved: 0
Deferred: 0
Blocked: 0

Executable/inspectable evidence:
- source inspection at abc123

Verification checkpoint:
- runtime reproduction

Unverified:
- runtime

Next recommended role/pass:
- verifier: reproduce runtime

Provenance:
- Generated by: test agent
- Source snapshot: abc123
"""


class RecordValidatorTests(unittest.TestCase):
    def test_review_record_is_auto_detected(self):
        self.assertEqual(validate(VALID_REVIEW), [])

    def test_retitled_review_is_detected_by_structure(self):
        text = VALID_REVIEW.replace("# Agent Relay Review", "# Review pass for PR 2")
        self.assertEqual(validate(text), [])

    def test_handoff_mentioning_review_title_is_not_misclassified(self):
        text = LEGACY_HANDOFF.replace(
            "- review completed",
            "- discussed `# Agent Relay Review` in completed-work prose",
        )
        self.assertEqual(validate(text), [])

    def test_review_requires_provenance(self):
        text = VALID_REVIEW.replace("## Provenance\n", "## Attribution\n")
        self.assertIn("missing heading: Provenance", validate(text))

    def test_review_requires_explicit_mutation_boundary(self):
        text = VALID_REVIEW.replace(
            "- Strictly read-only / forbidden: repository writes",
            "- No repository constraints recorded",
        )
        self.assertIn(
            "mutation boundary is not explicit (no read-only/forbidden statement)",
            validate(text),
        )

    def test_any_angle_bracket_placeholder_fails(self):
        for placeholder in (
            "<explicit | inferred>",
            "<count>",
            "<expected>",
            "<observed>",
            "<resources and exact prohibition>",
            "<agent/client>",
        ):
            with self.subTest(placeholder=placeholder):
                text = VALID_REVIEW.replace("test agent", placeholder)
                self.assertIn(
                    "template placeholders appear to remain unfilled",
                    validate(text),
                )

    def test_v02_handoff_without_new_optional_headings_remains_valid(self):
        self.assertEqual(validate(LEGACY_HANDOFF), [])

    def test_agent_pass_record_is_supported(self):
        self.assertEqual(validate(VALID_PASS), [])

    def test_agent_pass_placeholders_fail(self):
        text = VALID_PASS.replace("abc123", "<immutable-id>")
        self.assertIn("template placeholders appear to remain unfilled", validate(text))

    def test_unknown_record_kind_fails_closed(self):
        self.assertEqual(
            validate("# Miscellaneous note\n\nNothing structured here."),
            ["could not determine record kind; pass --kind"],
        )


FENCED_REVIEW_EXAMPLE = "# Agent Relay Review\n\n" + (
    "This pass was read-only. The record template is quoted below.\n\n"
    "```markdown\n"
    + "".join(
        f"## {heading}\nexample prose\n\n"
        for heading in (
            "Mission",
            "Reviewer profile",
            "Reviewed state",
            "Mutation boundaries",
            "Evidence baseline",
            "Findings summary",
            "Structured findings",
            "Executed or inspectable evidence",
            "Unverified surfaces",
            "Recommended next role/pass",
            "Readiness/sign-off status",
            "Provenance",
        )
    )
    + "```\n"
)


class FencedStructureTests(unittest.TestCase):
    def test_fenced_example_headings_do_not_satisfy_review_structure(self):
        errors = validate(FENCED_REVIEW_EXAMPLE, kind="review")
        self.assertTrue(
            any(error.startswith("missing heading:") for error in errors),
            f"fenced example wrongly satisfied review structure: {errors}",
        )

    def test_real_review_with_a_fenced_code_block_still_validates(self):
        self.assertEqual(validate(VALID_REVIEW), [])

    def test_agent_pass_record_requires_review_lenses(self):
        without = "\n".join(
            line
            for line in VALID_PASS.splitlines()
            if not line.startswith("Review lenses:")
        )
        self.assertIn("missing field: Review lenses:", validate(without, kind="pass"))


_REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent


def _documented_pass_record(filename: str) -> str:
    """Pull the agent-pass example out of a documentation file."""

    text = (_REPO_ROOT / filename).read_text(encoding="utf-8")
    match = re.search(r"```text\n(Agent pass:.*?)```", text, re.S)
    assert match, f"no agent-pass example found in {filename}"
    return re.sub(r"<[^>\n]+>", "x", match.group(1))


class RoundThreeRegressionTests(unittest.TestCase):
    def test_fenced_pass_record_is_not_a_durable_record(self):
        """A quoted template must not pass as an actual agent-pass record."""

        body = "\n".join(
            line for line in VALID_PASS.splitlines() if not line.startswith("# ")
        )
        quoted = "# Agent Pass Record\n\nExample only:\n\n```text\n" + body + "\n```\n"
        self.assertNotEqual(validate(quoted, kind="pass"), [])

    def test_documented_pass_records_satisfy_the_validator(self):
        """The docs' own examples must be copy-pasteable without errors."""

        for filename in ("SKILL.md", "README.md"):
            with self.subTest(filename=filename):
                self.assertEqual(
                    validate(_documented_pass_record(filename), kind="pass"), []
                )

    def test_boundary_statement_must_sit_in_the_boundary_section(self):
        """Unrelated prose elsewhere must not satisfy the one safety field."""

        text = VALID_REVIEW.replace(
            "- Strictly read-only / forbidden: repository writes",
            "- No constraints recorded",
        ).replace("- source inspection", "- forbidden API found in the parser")
        self.assertIn(
            "mutation boundary is not explicit (no read-only/forbidden statement)",
            validate(text),
        )

    def test_boundary_statement_inside_its_section_still_validates(self):
        self.assertEqual(validate(VALID_REVIEW), [])

    def test_handoff_boundary_may_sit_under_a_sub_heading(self):
        """The handoff template nests the prohibition under a `###` heading."""

        self.assertEqual(validate(LEGACY_HANDOFF), [])


if __name__ == "__main__":
    unittest.main()
