"""v0.5 structural tests: delegation briefs and authority provenance.

The v0.5 addition is orchestrated delegation, where authority reaches a
subordinate pass through an intermediary. A relayed statement about authority
is not authority, so the brief record fails closed: an asserted grant must cite
its grantor, its verbatim scope, and when it was granted, or the dispatching
agent must record the scope as its own judgment instead.
"""

import pathlib
import re
import unittest

from scripts.validate_handoff import _detect_kind, validate


VALID_BRIEF = """# Agent Relay Delegation Brief

## Mission
Repair the state-write symlink window.

## Mission mode
fix

## Lane
The state-write path only. The CLI construction path belongs to another lane.

## Authority provenance
- Source: owner-grant
- Grantor: mission owner
- Granted scope (verbatim): "fix the state-write symlink window"
- Granted at: 2026-09-05, against snapshot e6c6874

## Assurance profile
consequential

## Authoritative substrate
Repository under review.

## Current immutable snapshot
- Primary state: e6c6874
- Related states: none

## Mutation boundaries
### Allowed
- the state-write module and its regression module, in a private working copy

### Strictly read-only / forbidden
- durable records, review threads, and PR state are forbidden to this pass

## Bounds
- Cycle ID: C-1
- Pass bound: 1 of 3 passes in this cycle
- On exhaustion: return BOUND_EXHAUSTED, never a clean result

## Centrally owned derived claims
- test counts are owned by the dispatching agent; report the inputs instead

## Required deliverables
- a patch file carrying the fix and its regression

## Return contract
- Declared deviations: required, or `none`
- Claim maturity ceiling: EXECUTED

## Completion criteria
- the regression fails at the pre-fix state and passes with the fix

## Provenance
Generated by: test agent
Agent Relay role: Integrator
Source snapshot: e6c6874
"""


def _without_section(text: str, heading: str) -> str:
    """Drop one `##` section, keeping the rest of the record intact."""

    lines = text.splitlines()
    start = next(
        index for index, line in enumerate(lines) if line.strip() == f"## {heading}"
    )
    end = next(
        (
            index
            for index in range(start + 1, len(lines))
            if lines[index].startswith("## ")
        ),
        len(lines),
    )
    return "\n".join(lines[:start] + lines[end:])


def _with_empty_section(text: str, heading: str) -> str:
    """Keep one `##` heading but drop everything under it."""

    lines = text.splitlines()
    start = next(
        index for index, line in enumerate(lines) if line.strip() == f"## {heading}"
    )
    end = next(
        (
            index
            for index in range(start + 1, len(lines))
            if lines[index].startswith("## ")
        ),
        len(lines),
    )
    return "\n".join(lines[: start + 1] + [""] + lines[end:])


def _with_section_body(text: str, heading: str, body: str) -> str:
    """Replace one `##` section's body, keeping the heading."""

    lines = text.splitlines()
    start = next(
        index for index, line in enumerate(lines) if line.strip() == f"## {heading}"
    )
    end = next(
        (
            index
            for index in range(start + 1, len(lines))
            if lines[index].startswith("## ")
        ),
        len(lines),
    )
    return "\n".join(lines[: start + 1] + body.split("\n") + [""] + lines[end:])


def _untitled(text: str) -> str:
    """Drop the top-level title so detection must fall through to scoring."""

    return "\n".join(
        line for line in text.splitlines() if not line.startswith("# ")
    )


_REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
_HANDOFF_TEXT = (_REPO_ROOT / "assets" / "HANDOFF.md").read_text(encoding="utf-8")


class DelegationBriefValidatorTests(unittest.TestCase):
    """A brief is a distinct record kind with its own minimum."""

    def test_filled_brief_passes(self):
        self.assertEqual(validate(VALID_BRIEF), [])

    def test_brief_is_detected_from_its_title(self):
        # Discriminating control for the title map: this record is structurally
        # a handoff, so only `_TITLE_KIND` can return "brief" for it. Asserting
        # on VALID_BRIEF alone would pass with the title entry deleted, because
        # the structural-fit fallback returns "brief" for a compliant record.
        titled_but_not_brief_shaped = "# Agent Relay Delegation Brief\n" + _untitled(
            _HANDOFF_TEXT
        )
        self.assertEqual(_detect_kind(titled_but_not_brief_shaped), "brief")

    def test_brief_is_detected_from_structure_without_a_title(self):
        # Discriminating control for the kind-score table: with the title gone,
        # only the "brief" candidate score can return "brief".
        self.assertEqual(_detect_kind(_untitled(VALID_BRIEF)), "brief")

    def test_missing_required_heading_is_reported(self):
        text = _without_section(VALID_BRIEF, "Required deliverables")
        self.assertIn("missing heading: Required deliverables", validate(text))

    def test_brief_mutation_boundary_must_be_explicit(self):
        text = VALID_BRIEF.replace(
            "### Strictly read-only / forbidden\n"
            "- durable records, review threads, and PR state are forbidden to this pass",
            "### Notes\n- work carefully",
        )
        self.assertIn(
            "mutation boundary is not explicit (no read-only/forbidden statement)",
            validate(text),
        )

    def test_brief_shares_the_mission_mode_vocabulary(self):
        text = VALID_BRIEF.replace("## Mission mode\nfix", "## Mission mode\nrepair")
        self.assertIn("invalid mission mode: repair", validate(text))

    def test_adding_the_brief_kind_did_not_break_handoff_detection(self):
        self.assertEqual(_detect_kind(_HANDOFF_TEXT), "handoff")

    def test_untitled_handoff_still_outscores_the_fourth_candidate(self):
        # The titled assertion above returns from the title map before any
        # score is computed. This one exercises the scoring path, where the
        # fourth candidate competes with the handoff candidate.
        self.assertEqual(_detect_kind(_untitled(_HANDOFF_TEXT)), "handoff")


class AuthorityProvenanceTests(unittest.TestCase):
    """An asserted grant must be citable, or recorded as judgment."""

    def _errors(self, text):
        return [error for error in validate(text) if "authority provenance" in error]

    def test_owner_grant_without_a_grantor_is_refused(self):
        text = VALID_BRIEF.replace("- Grantor: mission owner", "- Grantor: N/A")
        self.assertTrue(
            any("Grantor" in error for error in self._errors(text)), self._errors(text)
        )

    def test_owner_grant_without_a_verbatim_scope_is_refused(self):
        text = VALID_BRIEF.replace(
            '- Granted scope (verbatim): "fix the state-write symlink window"',
            "- Granted scope (verbatim): none",
        )
        self.assertTrue(
            any("verbatim" in error for error in self._errors(text)), self._errors(text)
        )

    def test_owner_grant_without_a_grant_time_is_refused(self):
        text = VALID_BRIEF.replace(
            "- Granted at: 2026-09-05, against snapshot e6c6874",
            "- Granted at: unknown",
        )
        self.assertTrue(
            any("Granted at" in error for error in self._errors(text)),
            self._errors(text),
        )

    def test_a_dropped_grant_field_is_refused_like_an_empty_one(self):
        text = VALID_BRIEF.replace("- Grantor: mission owner\n", "")
        self.assertTrue(
            any("Grantor" in error for error in self._errors(text)), self._errors(text)
        )

    def test_delegated_grant_must_also_cite_its_grant(self):
        text = VALID_BRIEF.replace(
            "- Source: owner-grant", "- Source: delegated-grant"
        ).replace("- Grantor: mission owner", "- Grantor: N/A")
        self.assertTrue(
            any("delegated-grant" in error for error in self._errors(text)),
            self._errors(text),
        )

    def test_orchestrator_judgment_needs_no_grantor(self):
        text = (
            VALID_BRIEF.replace("- Source: owner-grant", "- Source: orchestrator-judgment")
            .replace("- Grantor: mission owner", "- Grantor: N/A")
            .replace(
                '- Granted scope (verbatim): "fix the state-write symlink window"',
                "- Granted scope (verbatim): N/A",
            )
            .replace(
                "- Granted at: 2026-09-05, against snapshot e6c6874",
                "- Granted at: N/A",
            )
        )
        self.assertEqual(validate(text), [])

    def test_no_conveyed_authority_needs_no_grantor(self):
        text = (
            VALID_BRIEF.replace("- Source: owner-grant", "- Source: none")
            .replace("- Grantor: mission owner", "- Grantor: N/A")
            .replace(
                '- Granted scope (verbatim): "fix the state-write symlink window"',
                "- Granted scope (verbatim): N/A",
            )
            .replace(
                "- Granted at: 2026-09-05, against snapshot e6c6874",
                "- Granted at: N/A",
            )
        )
        self.assertEqual(validate(text), [])

    def test_unrecognized_authority_source_is_refused(self):
        text = VALID_BRIEF.replace("- Source: owner-grant", "- Source: implied")
        self.assertIn("invalid authority provenance source: implied", validate(text))

    def test_absent_authority_source_is_refused(self):
        text = VALID_BRIEF.replace("- Source: owner-grant", "- Source: N/A")
        self.assertTrue(
            any("must declare an authority provenance source" in error for error in validate(text))
        )

    def test_a_fenced_example_cannot_supply_the_authority_source(self):
        text = VALID_BRIEF.replace(
            "- Source: owner-grant",
            "```\n- Source: owner-grant\n```",
        )
        self.assertTrue(
            any("must declare an authority provenance source" in error for error in validate(text))
        )


class DelegationBriefTemplateTests(unittest.TestCase):
    """The shipped template must satisfy the minimum it teaches."""

    ROOT = pathlib.Path(__file__).resolve().parent.parent

    def setUp(self):
        self.text = (self.ROOT / "assets" / "DELEGATION-BRIEF.md").read_text(
            encoding="utf-8"
        )

    def test_template_is_titled_as_a_brief(self):
        self.assertTrue(self.text.startswith("# Agent Relay Delegation Brief"))

    def test_template_carries_every_required_heading(self):
        from scripts.validate_handoff import BRIEF_REQUIRED_HEADINGS

        for heading in BRIEF_REQUIRED_HEADINGS:
            with self.subTest(heading=heading):
                self.assertIn(f"## {heading}", self.text)

    def test_template_carries_every_authority_provenance_field(self):
        for field in (
            "- Source:",
            "- Grantor:",
            "- Granted scope (verbatim):",
            "- Granted at:",
        ):
            with self.subTest(field=field):
                self.assertIn(field, self.text)

    def test_template_offers_the_whole_authority_vocabulary(self):
        for source in (
            "owner-grant",
            "delegated-grant",
            "orchestrator-judgment",
            "none",
        ):
            with self.subTest(source=source):
                self.assertIn(source, self.text)

    def test_template_requires_declared_deviations(self):
        self.assertIn("Declared deviations:", self.text)


class ProtocolV05DocumentationTests(unittest.TestCase):
    """Version and ownership invariants for the v0.5 additions."""

    ROOT = pathlib.Path(__file__).resolve().parent.parent

    def test_skill_and_readme_declare_the_same_version(self):
        skill = (self.ROOT / "SKILL.md").read_text(encoding="utf-8")
        readme = (self.ROOT / "README.md").read_text(encoding="utf-8")
        declared = next(
            line.split(":", 1)[1].strip().strip('"')
            for line in skill.splitlines()
            if line.strip().startswith("version:")
        )
        self.assertIn(f"**{declared}**", readme)

    def test_provenance_records_the_declared_version(self):
        skill = (self.ROOT / "SKILL.md").read_text(encoding="utf-8")
        declared = next(
            line.split(":", 1)[1].strip().strip('"')
            for line in skill.splitlines()
            if line.strip().startswith("version:")
        )
        provenance = (self.ROOT / "PROVENANCE.md").read_text(encoding="utf-8")
        self.assertIn(declared, provenance)

    def test_orchestrated_delegation_is_linked_from_the_skill(self):
        skill = (self.ROOT / "SKILL.md").read_text(encoding="utf-8")
        self.assertIn("references/orchestrated-delegation.md", skill)

    def test_delegation_brief_asset_is_linked_from_the_skill(self):
        skill = (self.ROOT / "SKILL.md").read_text(encoding="utf-8")
        self.assertIn("assets/DELEGATION-BRIEF.md", skill)

    def test_authority_vocabulary_has_exactly_one_owning_document(self):
        docs = list(self.ROOT.glob("*.md")) + list(self.ROOT.glob("*/*.md"))
        owners = [
            doc
            for doc in docs
            if "| `owner-grant` |" in doc.read_text(encoding="utf-8")
        ]
        self.assertEqual(
            [doc.name for doc in owners], ["orchestrated-delegation.md"]
        )

    def test_relayed_authority_rule_is_stated_in_the_rule_list(self):
        skill = (self.ROOT / "SKILL.md").read_text(encoding="utf-8")
        rules = skill.split("## Non-negotiable rules", 1)[1].split("\n## ", 1)[0]
        self.assertIn("Relayed authority is not authority", rules)


class ReviewRepairTests(unittest.TestCase):
    """Regressions for the findings of the independent review at 075ad5a."""

    ROOT = _REPO_ROOT

    def test_conveyed_grant_is_checked_outside_briefs(self):
        # R-04: rule 16 is not brief-specific. A handoff that claims an
        # owner grant without citing it must be refused, not skipped.
        handoff = _HANDOFF_TEXT.replace(
            "- Source: <owner-grant | delegated-grant | orchestrator-judgment | none>",
            "- Source: owner-grant",
        ).replace(
            "- Grantor: <who granted it; omit or `N/A` only when Source is "
            "orchestrator-judgment or none>",
            "- Grantor: N/A",
        )
        self.assertEqual(_detect_kind(handoff), "handoff")
        self.assertTrue(
            any(
                "authority provenance source owner-grant requires a named grantor"
                in error
                for error in validate(handoff)
            ),
            validate(handoff),
        )

    def test_a_record_without_the_section_is_unaffected(self):
        # The section stays optional for non-brief kinds, so records that were
        # valid before the check became reachable stay valid.
        without = _without_section(_HANDOFF_TEXT, "Authority provenance")
        self.assertFalse(
            [error for error in validate(without) if "authority provenance" in error]
        )

    def test_relayed_maturity_is_settled_in_the_owning_file(self):
        # R-02: the maturity vocabulary is owned by evidence-protocol.md, and
        # the subordinate/adopting split is stated there rather than only in
        # the two documents that do not own it.
        evidence = (self.ROOT / "references" / "evidence-protocol.md").read_text(
            encoding="utf-8"
        )
        self.assertIn("Maturity of a relayed or adopted claim", evidence)
        delegation = (
            self.ROOT / "references" / "orchestrated-delegation.md"
        ).read_text(encoding="utf-8")
        self.assertIn("Maturity of a relayed or adopted claim", delegation)
        # The contradicted phrasing must not come back: it made maturity a
        # function of who was reading the record.
        for doc in (self.ROOT / "SKILL.md", self.ROOT / "references" / "orchestrated-delegation.md"):
            self.assertNotIn(
                "regardless of what the subordinate pass ran",
                doc.read_text(encoding="utf-8"),
            )

    @staticmethod
    def _words(text):
        """Compare on words, so emphasis markers and wrapping do not matter."""

        # Only emphasis and code markers. Stripping `_` too would silently
        # mangle every underscored protocol token (BOUND_EXHAUSTED,
        # owner_grant), so an assertion on one could never match.
        return " ".join(re.sub(r"[*`]", "", text).split())

    def test_parallel_mutation_rule_is_not_weakened_for_lanes(self):
        # R-03: SKILL.md stated "unless disjointness is declared per lane"
        # twelve lines below the owned rule requiring demonstrable disjointness.
        skill = (self.ROOT / "SKILL.md").read_text(encoding="utf-8")
        self.assertNotIn("unless disjointness is declared", skill)
        section = skill.split("## Orchestrated delegation", 1)[1].split("\n## ", 1)[0]
        self.assertIn("demonstrably disjoint", self._words(section))
        delegation = self._words(
            (self.ROOT / "references" / "orchestrated-delegation.md").read_text(
                encoding="utf-8"
            )
        )
        # Anchor on the normative sentence, not on the file: the citation of
        # the owned rule higher up also contains "demonstrably disjoint", so a
        # bare substring check passes while this sentence is weakened.
        self.assertIn(
            "those surfaces must be demonstrably disjoint under the coordination "
            "scope's comparison rule",
            delegation,
        )
        # And the derived README summary, which drifted once already.
        readme = self._words((self.ROOT / "README.md").read_text(encoding="utf-8"))
        self.assertIn("requires demonstrably disjoint mutation surfaces", readme)

    def test_the_owned_parallel_mutation_rule_keeps_its_qualifier(self):
        # OL-1 from the repair review: the repair protected the derived
        # sentence in the orchestration section but not the owned rule the
        # derived sentence defers to.
        skill = self._words((self.ROOT / "SKILL.md").read_text(encoding="utf-8"))
        adapters = self._words(
            (self.ROOT / "references" / "runtime-adapters.md").read_text(
                encoding="utf-8"
            )
        )
        self.assertIn(
            "Parallel mutation MUST NOT proceed unless declared surfaces are "
            "demonstrably disjoint",
            skill,
        )
        # The owning file phrases the same requirement its own way. Both halves
        # of it must survive: disjointness has to be established, and anything
        # that cannot be shown disjoint counts as overlapping.
        self.assertIn("the surfaces are established disjoint", adapters)
        self.assertIn(
            "If two declared surfaces cannot be shown disjoint under that "
            "comparison rule, they are treated as overlapping.",
            adapters,
        )

    def test_enforcement_claims_state_what_the_check_cannot_do(self):
        # R-01: the durable record claimed the field made an ungranted
        # extension impossible to record silently. A structural check cannot
        # establish that a quotation is faithful.
        provenance = self._words(
            (self.ROOT / "PROVENANCE.md").read_text(encoding="utf-8")
        )
        self.assertNotIn("impossible to record silently", provenance)
        self.assertIn("cannot establish that the quoted scope is faithful", provenance)
        readme = self._words((self.ROOT / "README.md").read_text(encoding="utf-8"))
        self.assertNotIn("validated, fail-closed field", readme)
        # Anchor on the disclaimer being made, not on its exact wording.
        bullet = next(
            line
            for line in readme.split("- ")
            if line.startswith("Authority provenance")
        )
        self.assertIn("does not judge", bullet)

    def test_brief_minimum_carries_the_safety_bearing_fields(self):
        # R-08 / R-15: rule 14 names assurance profile and configured bounds
        # among the fields a runtime refuses a pass over rather than dropping.
        # They were template prose the validator never required.
        from scripts.validate_handoff import BRIEF_REQUIRED_HEADINGS

        for heading in ("Mission mode", "Assurance profile", "Bounds"):
            self.assertIn(heading, BRIEF_REQUIRED_HEADINGS)
            self.assertIn(
                f"missing heading: {heading}",
                validate(_without_section(VALID_BRIEF, heading)),
            )

    def test_dropping_the_assurance_profile_no_longer_skips_its_enum_check(self):
        # `_validate_enum_section` runs only over a section that exists, so an
        # optional Assurance profile could be removed to skip its own check.
        errors = validate(_without_section(VALID_BRIEF, "Assurance profile"))
        self.assertIn("missing heading: Assurance profile", errors)

    def test_re_derivation_requirement_survives_in_the_owning_file(self):
        # F-07 from the repair review: because orchestrated-delegation.md now
        # cites this requirement instead of restating it, weakening the one
        # paragraph would remove it from the corpus with nothing detecting it.
        evidence = self._words(
            (self.ROOT / "references" / "evidence-protocol.md").read_text(
                encoding="utf-8"
            )
        )
        self.assertIn(
            "the adopting agent MUST re-derive the discriminating control itself "
            "rather than accept a report of it",
            evidence,
        )
        delegation = self._words(
            (self.ROOT / "references" / "orchestrated-delegation.md").read_text(
                encoding="utf-8"
            )
        )
        self.assertIn("MUST re-derive the discriminating control itself", delegation)

    def test_maturity_is_not_relative_to_the_reader(self):
        # F-07: the sentence that resolves R-02 was invertible with the suite
        # green, as was the exact SKILL.md phrasing R-02 was raised against.
        evidence = self._words(
            (self.ROOT / "references" / "evidence-protocol.md").read_text(
                encoding="utf-8"
            )
        )
        self.assertIn("It is not relative to whoever is holding the record.", evidence)
        skill = self._words((self.ROOT / "SKILL.md").read_text(encoding="utf-8"))
        self.assertIn("in the dispatching agent's hands until it inspects", skill)

    def test_a_safety_bearing_brief_section_cannot_be_emptied(self):
        # F-05 from the repair review: requiring the heading closed deletion
        # but not emptying, and `_validate_enum_section` returns early on an
        # empty body — so the enum check was still skippable.
        for heading in ("Mission mode", "Assurance profile", "Bounds"):
            emptied = _with_empty_section(VALID_BRIEF, heading)
            self.assertIn(f"section is present but empty: {heading}", validate(emptied))

    def test_emptying_is_not_checked_for_the_older_record_kinds(self):
        # Scoped to the brief on purpose: the same strictness on a handoff
        # would refuse records that validate today.
        emptied = _with_empty_section(_HANDOFF_TEXT, "Assurance profile")
        self.assertEqual(_detect_kind(emptied), "handoff")
        self.assertFalse(
            [error for error in validate(emptied) if "present but empty" in error]
        )

    def test_the_delegated_return_ceiling_points_at_the_relay_rule(self):
        # Two sections of this file now describe the maturity of a delegated
        # return: the artifact-first bullet (from the cost-aware delegation
        # change) and the relayed-claim subsection. R-02 was raised because two
        # documents described maturity without pointing at each other.
        evidence = self._words(
            (self.ROOT / "references" / "evidence-protocol.md").read_text(
                encoding="utf-8"
            )
        )
        bullet = evidence.split("An accurate return is still at most", 1)[1].split(
            "See [", 1
        )[0]
        self.assertIn("Maturity of a relayed or adopted claim", bullet)

    def test_the_words_helper_preserves_protocol_tokens(self):
        # N-09: stripping `_` alongside the emphasis markers would silently
        # mangle every underscored token, so an assertion on one could never
        # match and an assertNotIn on one could never fail.
        self.assertEqual(self._words("`BOUND_EXHAUSTED`"), "BOUND_EXHAUSTED")
        self.assertEqual(self._words("*owner_grant*"), "owner_grant")
        self.assertEqual(self._words("**bold**  wrapped\ntext"), "bold wrapped text")

    def test_the_adopted_claim_floor_stays_conditional(self):
        # N-06/F-03: the flat "stays at EXECUTED" floor could be restored
        # verbatim with the suite green, and read literally it licensed
        # `EXECUTED` for an agent that had run nothing.
        evidence = self._words(
            (self.ROOT / "references" / "evidence-protocol.md").read_text(
                encoding="utf-8"
            )
        )
        self.assertIn(
            "the claim stays at the maturity the adopting agent's own evidence "
            "supports",
            evidence,
        )
        self.assertNotIn("the claim stays at EXECUTED with the reason recorded", evidence)

    def test_the_check_bound_is_described_accurately(self):
        # N-01/F-02: this text has now been wrong in three successive rounds,
        # each time describing a different set than `_ABSENT_VALUES` holds.
        from scripts.validate_handoff import _ABSENT_VALUES

        named = {token for token in _ABSENT_VALUES if token}
        for document in ("PROVENANCE.md", "README.md"):
            words = self._words((self.ROOT / document).read_text(encoding="utf-8"))
            self.assertNotIn("absent or placeholder", words)
            for token in named:
                self.assertIn(
                    token,
                    words.lower(),
                    f"{document} does not name the absence token {token!r}",
                )

    def test_bounds_cannot_be_reduced_to_a_token(self):
        # N-03: emptying is not the only way to drop a field. `Mission mode`
        # and `Assurance profile` are backstopped by their enum checks;
        # `Bounds` had nothing.
        for body in ("-", "---", ".", "### Details"):
            reduced = _with_section_body(VALID_BRIEF, "Bounds", body)
            self.assertTrue(
                [error for error in validate(reduced) if "bounds section" in error],
                f"{body!r} satisfied the Bounds requirement",
            )

    def test_a_fenced_example_cannot_satisfy_a_required_section(self):
        # N-03: `_section_body` blanks fences precisely so example structure
        # cannot satisfy the record's own requirement; the empty-section check
        # was not asking for that.
        fenced = _with_section_body(
            VALID_BRIEF, "Bounds", "```\n- Cycle ID: C-1\n- Pass bound: 1 of 3\n```"
        )
        errors = validate(fenced)
        self.assertIn("section is present but empty: Bounds", errors)

    def test_vocabulary_registry_lists_authority_provenance(self):
        # R-06: the registry that assigns each closed vocabulary an owning file
        # said four while the revision added a fifth.
        evidence = (self.ROOT / "references" / "evidence-protocol.md").read_text(
            encoding="utf-8"
        )
        registry = evidence.split("vocabularies", 1)[1].split("\n## ", 1)[0]
        row = next(
            line for line in registry.splitlines() if "Authority provenance" in line
        )
        for value in ("owner-grant", "delegated-grant", "orchestrator-judgment"):
            self.assertIn(value, row)
        self.assertIn("orchestrated-delegation.md", row)
        # The count in the heading has to move with the table.
        self.assertEqual(
            len([line for line in registry.splitlines() if line.strip().startswith("|")])
            - 2,  # header row and delimiter row
            5,
        )
        self.assertIn("five vocabularies", evidence)


# The main guard stays below every v0.5 test class so direct module execution
# cannot silently skip later classes (regression for upstream PR #12).
if __name__ == "__main__":
    unittest.main()
