#!/usr/bin/env python3
"""Lightweight structural validator for Agent Relay durable Markdown records.

Uses only the Python standard library. It does not interpret correctness,
permissions, or whether a role route is semantically appropriate; it checks
that handoff, review, and agent-pass records contain their minimum fields.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys

# Preserve the v0.2 handoff minimum so previously valid handoffs remain valid.
# v0.3 templates add Review lenses and Provenance as recommended transport fields.
HANDOFF_REQUIRED_HEADINGS = (
    "Mission",
    "Current role",
    "Role source",
    "Recommended role sequence",
    "Authoritative substrate",
    "Current immutable snapshot",
    "Mutation permissions",
    "Completed work",
    "Verified evidence",
    "Open findings",
    "Ordered next actions",
    "Verification checkpoint",
    "Completion criteria",
)

REVIEW_REQUIRED_HEADINGS = (
    "Mission",
    "Reviewer profile",
    "Reviewed state",
    "Mutation boundaries",
    "Evidence baseline",
    "Findings summary",
    "Structured findings",
    "Executed or inspectable evidence",
    "Unverified surfaces",
    "Recommended next role/pass",
    "Readiness/sign-off status",
    "Provenance",
)

PASS_REQUIRED_PREFIXES = (
    "Agent pass:",
    "Role:",
    "Review lenses:",
    "Role source:",
    "Role sequence:",
    "Reviewed/modified snapshot:",
    "Findings:",
    "Fixed:",
    "Disproved:",
    "Deferred:",
    "Blocked:",
    "Executable/inspectable evidence:",
    "Verification checkpoint:",
    "Unverified:",
    "Next recommended role/pass:",
    "Provenance:",
    "- Generated by:",
    "- Source snapshot:",
)

_TITLE_KIND = {
    "Agent Relay Handoff": "handoff",
    "Agent Relay Review": "review",
    "Agent Pass Record": "pass",
}

_PLACEHOLDER_RE = re.compile(r"<[^>\n]+>")


_FENCE_RE = re.compile(r"^\s*(?P<marker>`{3,}|~{3,})\s*(?P<info>\S*)")


def _outside_fences(text: str) -> list[str]:
    """Return the record's lines with fenced blocks blanked out.

    Markdown inside a fence is an example or a pasted template, never the
    record's own structure, so it must not satisfy a required heading.
    Blank lines replace fenced content to keep line positions stable.
    """

    lines: list[str] = []
    open_marker: str | None = None
    for line in text.splitlines():
        match = _FENCE_RE.match(line)
        if open_marker is None:
            if match:
                open_marker = match.group("marker")
                lines.append("")
                continue
            lines.append(line)
            continue
        # Inside a fence: only a same-character, at-least-as-long, bare
        # marker closes it.
        if (
            match
            and match.group("marker")[0] == open_marker[0]
            and len(match.group("marker")) >= len(open_marker)
            and not match.group("info")
        ):
            open_marker = None
        lines.append("")
    return lines


def _top_level_title(text: str) -> str | None:
    for line in _outside_fences(text):
        if line.startswith("# ") and not line.startswith("## "):
            return line[2:].strip()
    return None


def _headings(text: str) -> set[str]:
    return {
        line.lstrip("#").strip()
        for line in _outside_fences(text)
        if line.startswith("#")
    }


_BOUNDARY_SECTION = {
    "handoff": "Mutation permissions",
    "review": "Mutation boundaries",
}


def _section_body(text: str, heading: str) -> str:
    """Return the body under `heading`, up to the next same-or-higher heading.

    Sub-headings are kept, because the handoff template nests the boundary
    statement under `### Strictly read-only / forbidden`.
    """

    lines = text.splitlines()
    marks = _outside_fences(text)  # same length; fenced lines blanked
    start = None
    level = 0
    for index, mark in enumerate(marks):
        if mark.startswith("#") and mark.lstrip("#").strip() == heading:
            level = len(mark) - len(mark.lstrip("#"))
            start = index + 1
            break
    if start is None:
        return ""

    body: list[str] = []
    for index in range(start, len(lines)):
        mark = marks[index]
        if mark.startswith("#") and (
            len(mark) - len(mark.lstrip("#")) <= level
        ):
            break
        body.append(lines[index])
    return "\n".join(body)


def _prefixes_present(text: str, prefixes: tuple[str, ...]) -> int:
    stripped_lines = [line.strip() for line in _outside_fences(text)]
    return sum(
        1
        for prefix in prefixes
        if any(line.startswith(prefix) for line in stripped_lines)
    )


def _detect_kind(text: str) -> str:
    """Detect record kind from title first, then from structural fit."""

    title = _top_level_title(text)
    if title in _TITLE_KIND:
        return _TITLE_KIND[title]

    headings = _headings(text)
    scores = {
        "handoff": sum(h in headings for h in HANDOFF_REQUIRED_HEADINGS)
        / len(HANDOFF_REQUIRED_HEADINGS),
        "review": sum(h in headings for h in REVIEW_REQUIRED_HEADINGS)
        / len(REVIEW_REQUIRED_HEADINGS),
        "pass": _prefixes_present(text, PASS_REQUIRED_PREFIXES)
        / len(PASS_REQUIRED_PREFIXES),
    }

    best_kind, best_score = max(scores.items(), key=lambda item: item[1])
    second_score = sorted(scores.values(), reverse=True)[1]

    if best_score >= 0.5 and best_score - second_score >= 0.15:
        return best_kind

    return "unknown"


def validate(text: str, *, kind: str = "auto") -> list[str]:
    errors: list[str] = []
    selected_kind = _detect_kind(text) if kind == "auto" else kind
    if selected_kind not in {"handoff", "review", "pass"}:
        if kind == "auto":
            return ["could not determine record kind; pass --kind"]
        raise ValueError(f"unknown record kind: {selected_kind}")

    headings = _headings(text)

    if selected_kind == "handoff":
        for heading in HANDOFF_REQUIRED_HEADINGS:
            if heading not in headings:
                errors.append(f"missing heading: {heading}")
    elif selected_kind == "review":
        for heading in REVIEW_REQUIRED_HEADINGS:
            if heading not in headings:
                errors.append(f"missing heading: {heading}")
    else:
        stripped_lines = [line.strip() for line in _outside_fences(text)]
        for prefix in PASS_REQUIRED_PREFIXES:
            if not any(line.startswith(prefix) for line in stripped_lines):
                errors.append(f"missing field: {prefix}")

    if selected_kind in {"handoff", "review"}:
        # Scoped to the boundary section: unrelated prose elsewhere (an
        # evidence note mentioning a "forbidden API", say) must not satisfy
        # the record's one safety field.
        lowered = _section_body(
            text, _BOUNDARY_SECTION[selected_kind]
        ).lower()
        if "read-only" not in lowered and "forbidden" not in lowered:
            errors.append(
                "mutation boundary is not explicit (no read-only/forbidden statement)"
            )

    if _PLACEHOLDER_RE.search(text):
        errors.append("template placeholders appear to remain unfilled")

    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("record", type=Path)
    parser.add_argument(
        "--kind",
        choices=("auto", "handoff", "review", "pass"),
        default="auto",
    )
    args = parser.parse_args()

    try:
        text = args.record.read_text(encoding="utf-8")
    except OSError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    errors = validate(text, kind=args.kind)
    if errors:
        for error in errors:
            print(f"ERROR: {error}")
        return 1

    selected_kind = _detect_kind(text) if args.kind == "auto" else args.kind
    print(f"Agent Relay {selected_kind} structure: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
