#!/usr/bin/env python3
"""Lightweight structural validator for Agent Relay durable Markdown records.

Uses only the Python standard library. It does not interpret correctness,
permissions, or whether a role route is semantically appropriate; it checks
that handoff, review, and agent-pass records contain their minimum fields and
that optional safety-bearing metadata is structurally explicit when present.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys

# Preserve the v0.2 handoff minimum so previously valid handoffs remain valid.
# Later templates add review/authority/evidence fields as recommended transport
# metadata without invalidating older durable handoffs.
HANDOFF_REQUIRED_HEADINGS = (
    "Mission",
    "Current role",
    "Role source",
    "Recommended role sequence",
    "Authoritative substrate",
    "Current immutable snapshot",
    "Mutation permissions",
    "Completed work",
    "Verified evidence",
    "Open findings",
    "Ordered next actions",
    "Verification checkpoint",
    "Completion criteria",
)

REVIEW_REQUIRED_HEADINGS = (
    "Mission",
    "Reviewer profile",
    "Reviewed state",
    "Mutation boundaries",
    "Evidence baseline",
    "Findings summary",
    "Structured findings",
    "Executed or inspectable evidence",
    "Unverified surfaces",
    "Recommended next role/pass",
    "Readiness/sign-off status",
    "Provenance",
)

# Keep the v0.3 pass minimum for backward compatibility. v0.4 safety-bearing
# fields are validated when present rather than made retroactively mandatory.
PASS_REQUIRED_PREFIXES = (
    "Agent pass:",
    "Role:",
    "Review lenses:",
    "Role source:",
    "Role sequence:",
    "Reviewed/modified snapshot:",
    "Findings:",
    "Fixed:",
    "Disproved:",
    "Deferred:",
    "Blocked:",
    "Executable/inspectable evidence:",
    "Verification checkpoint:",
    "Unverified:",
    "Next recommended role/pass:",
    "Provenance:",
    "- Generated by:",
    "- Source snapshot:",
)

_TITLE_KIND = {
    "Agent Relay Handoff": "handoff",
    "Agent Relay Review": "review",
    "Agent Pass Record": "pass",
}

_PLACEHOLDER_RE = re.compile(r"<[^>\n]+>")
_FENCE_RE = re.compile(r"^\s*(?P<marker>`{3,}|~{3,})\s*(?P<info>\S*)")

MISSION_MODES = {
    "build",
    "fix",
    "test",
    "orchestrate",
    "operate",
    "understand",
    "plan",
    "analyze",
    "communicate",
    "n/a",
}
ASSURANCE_PROFILES = {"exploratory", "standard", "consequential", "n/a"}
EXECUTION_STATUSES = {"ran", "failed", "skipped", "n/a"}
TERMINATION_REASONS = {
    "no_new_findings",
    "bound_exhausted",
    "blocked",
    "cancelled",
    "n/a",
}


def _outside_fences(text: str) -> list[str]:
    """Return the record's lines with fenced blocks blanked out.

    Markdown inside a fence is an example or a pasted template, never the
    record's own structure, so it must not satisfy a required heading.
    Blank lines replace fenced content to keep line positions stable.
    """

    lines: list[str] = []
    open_marker: str | None = None
    for line in text.splitlines():
        match = _FENCE_RE.match(line)
        if open_marker is None:
            if match:
                open_marker = match.group("marker")
                lines.append("")
                continue
            lines.append(line)
            continue
        # Inside a fence: only a same-character, at-least-as-long, bare
        # marker closes it.
        if (
            match
            and match.group("marker")[0] == open_marker[0]
            and len(match.group("marker")) >= len(open_marker)
            and not match.group("info")
        ):
            open_marker = None
        lines.append("")
    return lines


def _top_level_title(text: str) -> str | None:
    for line in _outside_fences(text):
        if line.startswith("# ") and not line.startswith("## "):
            return line[2:].strip()
    return None


def _headings(text: str) -> set[str]:
    return {
        line.lstrip("#").strip()
        for line in _outside_fences(text)
        if line.startswith("#")
    }


_BOUNDARY_SECTION = {
    "handoff": "Mutation permissions",
    "review": "Mutation boundaries",
}


def _section_body(text: str, heading: str, *, strip_fences: bool = False) -> str:
    """Return the body under `heading`, up to the next same-or-higher heading.

    Sub-headings are kept, because the handoff template nests the boundary
    statement under `### Strictly read-only / forbidden`.

    With `strip_fences`, fenced lines come back blanked, matching how the rest
    of the validator reads records. Structural checks use that view so a table
    shown inside a fenced example is not mistaken for the record's own data.
    """

    lines = text.splitlines()
    marks = _outside_fences(text)  # same length; fenced lines blanked
    if strip_fences:
        lines = marks
    start = None
    level = 0
    for index, mark in enumerate(marks):
        if mark.startswith("#") and mark.lstrip("#").strip() == heading:
            level = len(mark) - len(mark.lstrip("#"))
            start = index + 1
            break
    if start is None:
        return ""

    body: list[str] = []
    for index in range(start, len(lines)):
        mark = marks[index]
        if mark.startswith("#") and (
            len(mark) - len(mark.lstrip("#")) <= level
        ):
            break
        body.append(lines[index])
    return "\n".join(body)


def _prefixes_present(text: str, prefixes: tuple[str, ...]) -> int:
    stripped_lines = [line.strip() for line in _outside_fences(text)]
    return sum(
        1
        for prefix in prefixes
        if any(line.startswith(prefix) for line in stripped_lines)
    )


def _line_value(text: str, prefix: str) -> str | None:
    for line in _outside_fences(text):
        stripped = line.strip()
        if stripped.startswith(prefix):
            return stripped[len(prefix):].strip()
    return None


def _claim_entries(text: str) -> list[str]:
    """Claim lines from a pass record's `Claims / evidence maturity` block.

    The block appears either as an inline value or as bullets beneath the
    label, so both shapes are collected.
    """

    lines = _outside_fences(text)
    entries: list[str] = []
    for index, line in enumerate(lines):
        if not line.strip().startswith("Claims / evidence maturity:"):
            continue
        inline = line.split(":", 1)[1].strip()
        if inline:
            entries.append(inline)
        for following in lines[index + 1:]:
            if not following.strip():
                break
            if not following.lstrip().startswith(("-", "*", "+")):
                break
            entries.append(following)
        break
    return entries


def _detect_kind(text: str) -> str:
    """Detect record kind from title first, then from structural fit."""

    title = _top_level_title(text)
    if title in _TITLE_KIND:
        return _TITLE_KIND[title]

    headings = _headings(text)
    scores = {
        "handoff": sum(h in headings for h in HANDOFF_REQUIRED_HEADINGS)
        / len(HANDOFF_REQUIRED_HEADINGS),
        "review": sum(h in headings for h in REVIEW_REQUIRED_HEADINGS)
        / len(REVIEW_REQUIRED_HEADINGS),
        "pass": _prefixes_present(text, PASS_REQUIRED_PREFIXES)
        / len(PASS_REQUIRED_PREFIXES),
    }

    best_kind, best_score = max(scores.items(), key=lambda item: item[1])
    second_score = sorted(scores.values(), reverse=True)[1]

    if best_score >= 0.5 and best_score - second_score >= 0.15:
        return best_kind

    return "unknown"


def _validate_enum_field(
    text: str,
    prefix: str,
    allowed: set[str],
    errors: list[str],
) -> None:
    value = _line_value(text, prefix)
    if value is None:
        return
    normalized = value.lower().replace("-", "_")
    if normalized not in allowed:
        errors.append(
            f"invalid {prefix.rstrip(':').lower()}: {value}"
        )


_TABLE_DELIM_RE = re.compile(r"^\s*\|?\s*:?-+:?\s*(\|\s*:?-+:?\s*)*\|?\s*$")
_UNESCAPED_PIPE_RE = re.compile(r"(?<!\\)\|")
_NO_FINDINGS_RE = re.compile(r"^[-*+\s]*(none|n/?a|no open findings)[.\s]*$", re.IGNORECASE)
CLAIM_MATURITIES = ("ASSERTED", "INSPECTED", "EXECUTED", "VERIFIED")
_MATURITY_SHAPED_RE = re.compile(r"\b[A-Z]{4,}\b")


def _table_cells(row: str) -> list[str]:
    """Split one markdown table row into trimmed cells.

    GFM permits an escaped pipe inside a cell. Splitting on every pipe would
    shift every column index to its right, so a snapshot column could be read
    from the wrong cell.
    """

    stripped = row.strip()
    if stripped.startswith("|"):
        stripped = stripped[1:]
    if stripped.endswith("|") and not stripped.endswith("\\|"):
        stripped = stripped[:-1]
    return [
        cell.strip().replace("\\|", "|")
        for cell in _UNESCAPED_PIPE_RE.split(stripped)
    ]


def _snapshot_column(header: list[str]) -> tuple[int | None, str | None]:
    """Locate the column that carries each finding's observation snapshot.

    Taking the first header merely containing "snapshot" lets an unrelated but
    filled column (a `Current snapshot`, say) stand in for an empty
    observation/reviewed column, which is the bypass this check exists to stop.
    Prefer the canonical column; accept a lone snapshot column; refuse to guess
    between several.
    """

    lowered = [name.lower() for name in header]
    canonical = [
        position
        for position, name in enumerate(lowered)
        if "snapshot" in name and ("observation" in name or "reviewed" in name)
    ]
    if canonical:
        return canonical[0], None

    snapshots = [p for p, name in enumerate(lowered) if "snapshot" in name]
    if not snapshots:
        return None, "open finding table must preserve an observation/reviewed snapshot"
    if len(snapshots) > 1:
        return None, (
            "open finding table has several snapshot columns; name the canonical "
            "observation/reviewed snapshot column"
        )
    return snapshots[0], None


def _finding_table_errors(section: str) -> list[str]:
    """Require each carried finding to actually record its observation snapshot.

    A substring test for "snapshot" over the section is satisfied by the
    template's own header row, so a table whose snapshot cells are all empty --
    or a section reading "no snapshot was recorded" -- would pass while
    preserving nothing. The canonical column must exist *and* every data row
    must fill it.

    Findings recorded as free prose are refused rather than parsed: arbitrary
    prose cannot be split into findings reliably, so per-finding snapshots
    cannot be enforced there. A section declaring no findings is still fine.
    """

    lines = section.splitlines()
    header_index = None
    for index in range(1, len(lines)):
        if _TABLE_DELIM_RE.match(lines[index]) and "|" in lines[index]:
            if "|" in lines[index - 1]:
                header_index = index - 1
                break

    if header_index is None:
        if all(not line.strip() or _NO_FINDINGS_RE.match(line) for line in lines):
            return []
        return [
            "open findings must use the finding table so each row records its "
            "observation/reviewed snapshot (or say `None.`)"
        ]

    column, error = _snapshot_column(_table_cells(lines[header_index]))
    if error:
        return [error]

    missing: list[str] = []
    for row in lines[header_index + 2:]:
        if not row.strip() or "|" not in row or _TABLE_DELIM_RE.match(row):
            continue
        cells = _table_cells(row)
        if column >= len(cells) or not cells[column]:
            missing.append(cells[0] if cells and cells[0] else "(unnamed)")
    if missing:
        return [
            "open finding rows are missing their observation/reviewed snapshot: "
            + ", ".join(missing)
        ]
    return []


def _claim_maturity_errors(entries: list[str]) -> list[str]:
    """Reject a claim that declares a maturity outside the vocabulary.

    Presence is not required: a record may describe a claim without grading it,
    and the documented templates must stay copy-pasteable. What must not pass is
    a claim asserting a maturity that does not exist, which would otherwise read
    as a graded claim while meaning nothing.
    """

    errors = []
    for entry in entries:
        text = entry.strip().lstrip("-*+ ").strip()
        if not text or _NO_FINDINGS_RE.match(entry):
            continue
        if any(token in entry for token in CLAIM_MATURITIES):
            continue
        declared = _MATURITY_SHAPED_RE.findall(entry)
        if declared:
            errors.append(
                f"claim declares an unrecognized maturity {declared[0]}: {text}"
            )
    return errors


def _validate_enum_section(
    text: str,
    heading: str,
    allowed: set[str],
    errors: list[str],
) -> None:
    body = _section_body(text, heading).strip()
    if not body:
        return
    value = body.splitlines()[0].strip()
    if not value:
        return
    normalized = value.lower().replace("-", "_")
    if normalized not in allowed:
        errors.append(f"invalid {heading.lower()}: {value}")


def validate(text: str, *, kind: str = "auto") -> list[str]:
    errors: list[str] = []
    selected_kind = _detect_kind(text) if kind == "auto" else kind
    if selected_kind not in {"handoff", "review", "pass"}:
        if kind == "auto":
            return ["could not determine record kind; pass --kind"]
        raise ValueError(f"unknown record kind: {selected_kind}")

    headings = _headings(text)

    if selected_kind == "handoff":
        for heading in HANDOFF_REQUIRED_HEADINGS:
            if heading not in headings:
                errors.append(f"missing heading: {heading}")
    elif selected_kind == "review":
        for heading in REVIEW_REQUIRED_HEADINGS:
            if heading not in headings:
                errors.append(f"missing heading: {heading}")
    else:
        stripped_lines = [line.strip() for line in _outside_fences(text)]
        for prefix in PASS_REQUIRED_PREFIXES:
            if not any(line.startswith(prefix) for line in stripped_lines):
                errors.append(f"missing field: {prefix}")

    if selected_kind in {"handoff", "review"}:
        # Scoped to the boundary section: unrelated prose elsewhere (an
        # evidence note mentioning a "forbidden API", say) must not satisfy
        # the record's one safety field.
        lowered = _section_body(
            text, _BOUNDARY_SECTION[selected_kind]
        ).lower()
        if "read-only" not in lowered and "forbidden" not in lowered:
            errors.append(
                "mutation boundary is not explicit (no read-only/forbidden statement)"
            )

    if selected_kind == "handoff":
        open_findings = _section_body(
            text, "Open findings", strip_fences=True
        ).strip()
        if not open_findings:
            errors.append("open findings section must say `None.` or carry findings")
        errors.extend(_finding_table_errors(open_findings))

        errors.extend(
            _claim_maturity_errors(
                _section_body(
                    text,
                    "Completed but not independently verified",
                    strip_fences=True,
                ).splitlines()
            )
        )

        # Handoffs carry the v0.4 vocabularies as sections, not as `Key:` lines,
        # so they need section-shaped validation or the vocabulary is unchecked
        # on the protocol's primary transport.
        _validate_enum_section(text, "Mission mode", MISSION_MODES, errors)
        _validate_enum_section(text, "Assurance profile", ASSURANCE_PROFILES, errors)

    if selected_kind == "pass":
        boundary = _line_value(text, "Mutation boundary:")
        if boundary is not None:
            lowered = boundary.lower()
            if "read-only" not in lowered and "forbidden" not in lowered and "allowed" not in lowered:
                errors.append(
                    "pass mutation boundary is not explicit (no allowed/read-only/forbidden statement)"
                )

        errors.extend(_claim_maturity_errors(_claim_entries(text)))

        _validate_enum_field(text, "Mission mode:", MISSION_MODES, errors)
        _validate_enum_field(text, "Assurance profile:", ASSURANCE_PROFILES, errors)
        _validate_enum_field(text, "Execution status:", EXECUTION_STATUSES, errors)
        _validate_enum_field(text, "Termination reason:", TERMINATION_REASONS, errors)

    if _PLACEHOLDER_RE.search(text):
        errors.append("template placeholders appear to remain unfilled")

    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("record", type=Path)
    parser.add_argument(
        "--kind",
        choices=("auto", "handoff", "review", "pass"),
        default="auto",
    )
    args = parser.parse_args()

    try:
        text = args.record.read_text(encoding="utf-8")
    except OSError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    errors = validate(text, kind=args.kind)
    if errors:
        for error in errors:
            print(f"ERROR: {error}")
        return 1

    selected_kind = _detect_kind(text) if args.kind == "auto" else args.kind
    print(f"Agent Relay {selected_kind} structure: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
